### ISSUE TITLE
See "This should be 1, 1 and then the app should still work (this reveals a bug)"

### ISSUE THREAD

**Issue by jopvanheesch** [languageininteraction/TacitCommunicationGame#114]

**Comment by Woseseltops** [comment]
As far as I can see, this works as intended. 

To see it in action, make sure the level generator is disabled (for example, by immediately returning the basic level as it is created), because the level generator assumes a square and at least 4 empty spots. I could make it more intelligent in this respect, but this would take time we don't have.
